/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShirinTalkRouteImport } from './routes/shirin-talk'
import { Route as MywordieRouteImport } from './routes/mywordie'
import { Route as IndexRouteImport } from './routes/index'

const ShirinTalkRoute = ShirinTalkRouteImport.update({
  id: '/shirin-talk',
  path: '/shirin-talk',
  getParentRoute: () => rootRouteImport,
} as any)
const MywordieRoute = MywordieRouteImport.update({
  id: '/mywordie',
  path: '/mywordie',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mywordie': typeof MywordieRoute
  '/shirin-talk': typeof ShirinTalkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mywordie': typeof MywordieRoute
  '/shirin-talk': typeof ShirinTalkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mywordie': typeof MywordieRoute
  '/shirin-talk': typeof ShirinTalkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mywordie' | '/shirin-talk'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mywordie' | '/shirin-talk'
  id: '__root__' | '/' | '/mywordie' | '/shirin-talk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MywordieRoute: typeof MywordieRoute
  ShirinTalkRoute: typeof ShirinTalkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shirin-talk': {
      id: '/shirin-talk'
      path: '/shirin-talk'
      fullPath: '/shirin-talk'
      preLoaderRoute: typeof ShirinTalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mywordie': {
      id: '/mywordie'
      path: '/mywordie'
      fullPath: '/mywordie'
      preLoaderRoute: typeof MywordieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MywordieRoute: MywordieRoute,
  ShirinTalkRoute: ShirinTalkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
